# Generated by Django 5.2.16 on 2026-07-31 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ColoringBook',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                (
                    'publisher',
                    models.CharField(blank=True, max_length=255, verbose_name='Издательство'),
                ),
                (
                    'cover',
                    models.ImageField(
                        blank=True, upload_to='books/covers/', verbose_name='Обложка'
                    ),
                ),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Раскраска',
                'verbose_name_plural': 'Раскраски',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TrackerUser',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'telegram_id',
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name='Telegram ID'
                    ),
                ),
                (
                    'session_key',
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('photo_url', models.URLField(blank=True, max_length=500, verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Пользователь трекера',
                'verbose_name_plural': 'Пользователи трекера',
            },
        ),
        migrations.CreateModel(
            name='ColoringPage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(verbose_name='Первая страница')),
                (
                    'spread_end',
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name='Последняя страница разворота'
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pages',
                        to='app.coloringbook',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Страница / разворот',
                'verbose_name_plural': 'Страницы / развороты',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorited_by',
                        to='app.coloringbook',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorites',
                        to='app.trackeruser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Избранная раскраска',
                'verbose_name_plural': 'Избранные раскраски',
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_books',
                        to='app.coloringbook',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='books',
                        to='app.trackeruser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Книга пользователя',
                'verbose_name_plural': 'Книги пользователей',
            },
        ),
        migrations.CreateModel(
            name='ColoringWork',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'photo',
                    models.ImageField(
                        blank=True, upload_to='works/%Y/%m/', verbose_name='Фото работы'
                    ),
                ),
                (
                    'completed_at',
                    models.DateField(auto_now_add=True, verbose_name='Дата завершения'),
                ),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Заметка')),
                (
                    'page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='works',
                        to='app.coloringpage',
                    ),
                ),
                (
                    'user_book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='works',
                        to='app.userbook',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Раскрашенная работа',
                'verbose_name_plural': 'Раскрашенные работы',
            },
        ),
        migrations.AddConstraint(
            model_name='coloringpage',
            constraint=models.UniqueConstraint(
                fields=('book', 'number'), name='unique_coloring_page'
            ),
        ),
        migrations.AddConstraint(
            model_name='favoritebook',
            constraint=models.UniqueConstraint(
                fields=('user', 'book'), name='unique_favorite_coloring_book'
            ),
        ),
        migrations.AddConstraint(
            model_name='userbook',
            constraint=models.UniqueConstraint(
                fields=('book', 'user'), name='unique_user_coloring_book'
            ),
        ),
        migrations.AddConstraint(
            model_name='coloringwork',
            constraint=models.UniqueConstraint(
                fields=('user_book', 'page'), name='unique_coloring_work'
            ),
        ),
    ]
