# Generated by Django 5.2 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeruser',
            name='webapp_viewport_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота WebApp'),
        ),
        migrations.AddField(
            model_name='trackeruser',
            name='webapp_viewport_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина WebApp'),
        ),
    ]
