# Generated by Django 5.2.16 on 2026-08-02

from django.db import migrations, models

FLOWERS = [
    '🌸',
    '🌷',
    '🌹',
    '🌺',
    '🌻',
    '🌼',
    '💐',
    '🏵️',
    '🪻',
    '🪷',
    '🥀',
    '🌾',
    '💮',
    '🪴',
    '☘️',
    '🍀',
    '🪺',
    '🌿',
    '🍃',
    '🦋',
]


def assign_existing_flowers(apps, schema_editor):
    ColoringWork = apps.get_model('app', 'ColoringWork')
    used_by_day = {}
    for work in ColoringWork.objects.order_by('completed_at', 'id'):
        key = (work.user_book.user_id, work.completed_at)
        used = used_by_day.setdefault(key, set())
        flower = next(
            (item for item in FLOWERS if item not in used), FLOWERS[work.id % len(FLOWERS)]
        )
        work.flower_icon = flower
        work.save(update_fields=['flower_icon'])
        used.add(flower)


class Migration(migrations.Migration):
    dependencies = [('app', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='coloringwork',
            name='flower_icon',
            field=models.CharField(
                choices=[
                    ('🌸', '🌸'),
                    ('🌷', '🌷'),
                    ('🌹', '🌹'),
                    ('🌺', '🌺'),
                    ('🌻', '🌻'),
                    ('🌼', '🌼'),
                    ('💐', '💐'),
                    ('🏵️', '🏵️'),
                    ('🪻', '🪻'),
                    ('🪷', '🪷'),
                    ('🥀', '🥀'),
                    ('🌾', '🌾'),
                    ('💮', '💮'),
                    ('🪴', '🪴'),
                    ('☘️', '☘️'),
                    ('🍀', '🍀'),
                    ('🪺', '🪺'),
                    ('🌿', '🌿'),
                    ('🍃', '🍃'),
                    ('🦋', '🦋'),
                ],
                default='🌸',
                max_length=8,
                verbose_name='Цветок в отчёте',
            ),
        ),
        migrations.RunPython(assign_existing_flowers, migrations.RunPython.noop),
    ]
