# Generated by Django 5.2.16 on 2026-08-02

from django.db import migrations, models

FLOWER_CHOICES = [
    ('🌸', '🌸'),
    ('🌷', '🌷'),
    ('🌹', '🌹'),
    ('🌺', '🌺'),
    ('🌻', '🌻'),
    ('🌼', '🌼'),
    ('💐', '💐'),
    ('🏵️', '🏵️'),
    ('🪻', '🪻'),
    ('🪷', '🪷'),
    ('🥀', '🥀'),
    ('🌾', '🌾'),
    ('💮', '💮'),
    ('🪴', '🪴'),
    ('☘️', '☘️'),
    ('🍀', '🍀'),
    ('🪺', '🪺'),
    ('🌿', '🌿'),
    ('🍃', '🍃'),
    ('🦋', '🦋'),
]


class Migration(migrations.Migration):
    dependencies = [('app', '0002_coloringwork_flower_icon')]

    operations = [
        migrations.AddField(
            model_name='coloringbook',
            name='report_icon',
            field=models.CharField(
                blank=True, choices=FLOWER_CHOICES, max_length=8, verbose_name='Значок в отчёте'
            ),
        ),
        migrations.RemoveField(model_name='coloringwork', name='flower_icon'),
    ]
