# Generated by Django 5.2 on 2026-08-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trackeruser_webapp_viewport'),
    ]

    operations = [
        migrations.DeleteModel(name='FavoriteBook'),
    ]
