# Generated by Django 5.2.16 on 2026-08-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_coloringbook_report_icon_remove_coloringwork_flower_icon'),
        ('app', '0003_remove_favoritebook'),
    ]

    operations = []
