# Generated by Django 5.2.16 on 2026-08-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_merge_20260802_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbook',
            options={
                'verbose_name': 'Раскраска пользователя',
                'verbose_name_plural': 'Раскраски пользователей',
            },
        ),
    ]
