# Generated by Django 5.2.16 on 2026-08-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_alter_userbook_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoringColorCode',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'image',
                    models.ImageField(upload_to='color-codes/%Y/%m/', verbose_name='Цветовой код'),
                ),
                (
                    'page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='color_codes',
                        to='app.coloringpage',
                    ),
                ),
                (
                    'user_book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='color_codes',
                        to='app.userbook',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Цветовой код',
                'verbose_name_plural': 'Цветовые коды',
            },
        ),
        migrations.AddConstraint(
            model_name='coloringcolorcode',
            constraint=models.UniqueConstraint(
                fields=('user_book', 'page'), name='unique_coloring_color_code'
            ),
        ),
    ]
