# Generated by Django 5.2.16 on 2026-08-02

import django.db.models.deletion
from django.db import migrations, models


def preserve_existing_work_photos(apps, schema_editor):
    ColoringWork = apps.get_model('app', 'ColoringWork')
    ColoringPagePhoto = apps.get_model('app', 'ColoringPagePhoto')
    for work in ColoringWork.objects.exclude(photo='').iterator():
        ColoringPagePhoto.objects.get_or_create(
            user_book_id=work.user_book_id,
            page_id=work.page_id,
            defaults={'image': work.photo.name},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0006_coloringcolorcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoringPagePhoto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='works/%Y/%m/', verbose_name='Фото работы')),
                (
                    'page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='page_photos',
                        to='app.coloringpage',
                    ),
                ),
                (
                    'user_book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='page_photos',
                        to='app.userbook',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Фото работы',
                'verbose_name_plural': 'Фотографии работ',
            },
        ),
        migrations.AddConstraint(
            model_name='coloringpagephoto',
            constraint=models.UniqueConstraint(
                fields=('user_book', 'page'), name='unique_coloring_page_photo'
            ),
        ),
        migrations.RunPython(preserve_existing_work_photos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='coloringwork',
            name='photo',
        ),
    ]
