# Generated by Django 5.2.16 on 2026-08-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_coloringpagephoto_remove_coloringwork_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloringwork',
            name='hide_in_report',
            field=models.BooleanField(default=False, verbose_name='Не отображать в статистике'),
        ),
    ]
