# Generated by Django 5.2.17 on 2026-08-07 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_coloringwork_hide_in_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoringSuggestion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='Название раскраски')),
                ('source_text', models.TextField(blank=True, verbose_name='Ссылка или источник')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='Отпечаток')),
                (
                    'notification_sent_at',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Уведомление отправлено'
                    ),
                ),
                (
                    'notification_error',
                    models.TextField(blank=True, verbose_name='Ошибка уведомления'),
                ),
                ('admin_reply', models.TextField(blank=True, verbose_name='Ответ пользователю')),
                (
                    'reply_sent_at',
                    models.DateTimeField(blank=True, null=True, verbose_name='Ответ отправлен'),
                ),
                ('reply_error', models.TextField(blank=True, verbose_name='Ошибка ответа')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='suggestions',
                        to='app.trackeruser',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Предложение раскраски',
                'verbose_name_plural': 'Предложения раскрасок',
                'ordering': ('-created_at',),
                'constraints': [
                    models.UniqueConstraint(
                        fields=('user', 'fingerprint'), name='unique_user_coloring_suggestion'
                    )
                ],
            },
        ),
    ]
