# Generated by Django 5.2.17 on 2026-08-08 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0009_coloringsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloringbook',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='personal_coloring_books',
                to='app.trackeruser',
                verbose_name='Владелец личной раскраски',
            ),
        ),
    ]
