# Generated by Django 5.2.17 on 2026-08-08

from django.db import migrations, models

FLOWER_CHOICES = [
    ('🌸', '🌸'),
    ('🌷', '🌷'),
    ('🌹', '🌹'),
    ('🌺', '🌺'),
    ('🌻', '🌻'),
    ('🌼', '🌼'),
    ('💐', '💐'),
    ('🏵️', '🏵️'),
    ('🪻', '🪻'),
    ('🪷', '🪷'),
    ('🥀', '🥀'),
    ('🌾', '🌾'),
    ('💮', '💮'),
    ('🪴', '🪴'),
    ('☘️', '☘️'),
    ('🍀', '🍀'),
    ('🪺', '🪺'),
    ('🌿', '🌿'),
    ('🍃', '🍃'),
    ('🦋', '🦋'),
    ('🌱', '🌱'),
    ('🌲', '🌲'),
    ('🌳', '🌳'),
    ('🌴', '🌴'),
    ('🌵', '🌵'),
    ('🎋', '🎋'),
    ('🎍', '🎍'),
    ('🍁', '🍁'),
    ('🍂', '🍂'),
    ('🍄', '🍄'),
    ('🌰', '🌰'),
]


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0010_coloringbook_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloringbook',
            name='report_icon',
            field=models.CharField(
                blank=True,
                choices=FLOWER_CHOICES,
                max_length=8,
                verbose_name='Значок в отчёте',
            ),
        ),
    ]
