# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0011_alter_coloringbook_report_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloringbook',
            name='cover_original',
            field=models.ImageField(
                blank=True,
                upload_to='books/cover-originals/',
                verbose_name='Исходник обложки',
            ),
        ),
        migrations.AddField(
            model_name='coloringcolorcode',
            name='original_image',
            field=models.ImageField(
                blank=True,
                upload_to='color-codes/originals/%Y/%m/',
                verbose_name='Исходник цветового кода',
            ),
        ),
        migrations.AddField(
            model_name='coloringpagephoto',
            name='original_image',
            field=models.ImageField(
                blank=True,
                upload_to='works/originals/%Y/%m/',
                verbose_name='Исходник фото работы',
            ),
        ),
    ]
