# Generated by Django 5.2.17 on 2026-08-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0014_stardonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stardonation',
            name='notification_chat_id',
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name='ID чата уведомлений'
            ),
        ),
        migrations.AddField(
            model_name='stardonation',
            name='notification_error',
            field=models.TextField(blank=True, verbose_name='Ошибка уведомления'),
        ),
        migrations.AddField(
            model_name='stardonation',
            name='notification_message_id',
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name='ID сообщения уведомления'
            ),
        ),
        migrations.AddField(
            model_name='stardonation',
            name='notification_sent_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Уведомление отправлено'
            ),
        ),
    ]
