# Generated by Django 5.2.17 on 2026-09-11 07:24

from django.db import migrations, models


def backfill_cover_previews(apps, schema_editor):
    from app.image_previews import build_cover_preview

    ColoringBook = apps.get_model('app', 'ColoringBook')
    for book in ColoringBook.objects.exclude(cover='').iterator():
        try:
            name, preview_file = build_cover_preview(book.cover)
            book.cover_preview.save(name, preview_file, save=False)
            book.save(update_fields=('cover_preview',))
        except (OSError, ValueError):
            # A broken legacy file must not make the database migration fail.
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_randomizerrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloringbook',
            name='cover_preview',
            field=models.ImageField(blank=True, editable=False, upload_to='books/cover-previews/', verbose_name='Превью обложки'),
        ),
        migrations.RunPython(backfill_cover_previews, migrations.RunPython.noop),
    ]
