# Generated by Django 5.2.17 on 2026-09-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_marker_number_and_palette_symbols'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marker',
            options={'ordering': ('manufacturer', 'number', 'symbol'), 'verbose_name': 'Маркер', 'verbose_name_plural': 'Маркеры'},
        ),
        migrations.RemoveConstraint(
            model_name='marker',
            name='unique_marker_number',
        ),
        migrations.AddField(
            model_name='marker',
            name='manufacturer',
            field=models.CharField(choices=[('unknown', 'Не указан'), ('copic', 'Copic'), ('ohuhu', 'Ohuhu'), ('tombow', 'Tombow'), ('karin', 'Karin'), ('winsor_newton', 'Winsor & Newton'), ('arrtx', 'Arrtx'), ('spectrum_noir', 'Spectrum Noir'), ('prismacolor', 'Prismacolor'), ('faber_castell', 'Faber-Castell'), ('pentel', 'Pentel'), ('touch', 'Touch')], default='unknown', max_length=32, verbose_name='Производитель'),
        ),
        migrations.AddConstraint(
            model_name='marker',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'number'), name='unique_marker_manufacturer_number'),
        ),
    ]
