# Generated by Django 5.2.17 on 2026-09-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_marker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='manufacturer',
            field=models.CharField(choices=[('flysea', 'Flysea'), ('guangna', 'Guangna'), ('grasp', 'Grasp'), ('infiart', 'Infiart'), ('languo', 'Languo'), ('rosymeng', 'Rosymeng'), ('nusoulra', 'Nusoulra'), ('unknown', 'Не указан')], default='unknown', max_length=32, verbose_name='Производитель'),
        ),
    ]
