# Generated by Django 5.2.17 on 2026-09-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_marker_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='manufacturer',
            field=models.CharField(choices=[('flysea', 'Flysea'), ('guangna', 'GuangNa'), ('grasp', 'GRASP'), ('infiart', 'Infiart'), ('languo', 'Languo'), ('rosymeng', 'ROSYMENG'), ('nusoulra', 'NuSoulra'), ('tooli_art', 'Tooli-Art'), ('nicety', 'NICETY'), ('unknown', 'Не указан')], default='unknown', max_length=32, verbose_name='Производитель'),
        ),
    ]
