# Generated by Django 5.2.17 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_marker_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='marker_type',
            field=models.CharField(
                choices=[('marker', 'Маркер'), ('pen', 'Ручка')],
                default='marker',
                max_length=16,
                verbose_name='Тип',
            ),
        ),
        migrations.AlterModelOptions(
            name='marker',
            options={
                'ordering': ('manufacturer', 'marker_type', 'number', 'symbol'),
                'verbose_name': 'Маркер или ручка',
                'verbose_name_plural': 'Маркеры и ручки',
            },
        ),
        migrations.RemoveConstraint(
            model_name='marker',
            name='unique_marker_manufacturer_number',
        ),
        migrations.AddConstraint(
            model_name='marker',
            constraint=models.UniqueConstraint(
                fields=('manufacturer', 'marker_type', 'number'),
                name='unique_marker_type_manufacturer_number',
            ),
        ),
    ]
