# Generated by Django 5.2.17 on 2026-09-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_marker_type_and_number_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_stock', to='app.marker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_stock', to='app.trackeruser')),
            ],
            options={
                'verbose_name': 'Запас маркера',
                'verbose_name_plural': 'Запасы маркеров',
                'ordering': ('marker__manufacturer', 'marker__marker_type', 'marker__number'),
                'constraints': [models.UniqueConstraint(fields=('user', 'marker'), name='unique_user_marker_stock')],
            },
        ),
    ]
